name: hostel_management
description: A hostel complaint management app
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # 🔑 Auth + backend
  firebase_core: ^3.14.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.1

  # state‑management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mobile.jpg
