// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJLDumeLJEe4oNICSiRje9buQVikH36Lg',
    appId: '1:190237776577:web:e1d62ad6ce352f3bf01240',
    messagingSenderId: '190237776577',
    projectId: 'hostel-ease-42729',
    authDomain: 'hostel-ease-42729.firebaseapp.com',
    storageBucket: 'hostel-ease-42729.firebasestorage.app',
    measurementId: 'G-9B2DVL4SKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-KIfsgdeKygu_smWwpdlfM1pwa6tWDLI',
    appId: '1:190237776577:android:693136259f163db1f01240',
    messagingSenderId: '190237776577',
    projectId: 'hostel-ease-42729',
    storageBucket: 'hostel-ease-42729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRe02yDa5QzlKkL5nnKuzb2Pn3x6sBpx8',
    appId: '1:190237776577:ios:27bf6e579e57c1c5f01240',
    messagingSenderId: '190237776577',
    projectId: 'hostel-ease-42729',
    storageBucket: 'hostel-ease-42729.firebasestorage.app',
    iosClientId: '190237776577-mj5c969tes8qo6ac2vn1ov7m8m7ooick.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelManagement',
  );

}